### PR TITLE
Fixed bug which caused form status not updateable

### LINKED ISSUE #52: Required fields block changing the reply state

### PR DESCRIPTION
**Pull request by hkurhinen**
fixes #52

### CODE REVIEW

File: form/index.js [hunk 1]
```diff
@@ -27,6 +27,29 @@
...
+          return true;
+        }
+
+        return Form.validateFieldVisibilityRule(reply, section['visible-if']);
+      });
+      
+      for (let i = 0; i < formConfig.sections.length; i++) {
+        const section = formConfig.sections[i];
+        const sectionFields = section.fields;
+        section.fields = _.filter(section.fields, (field) => { return Form.validateFieldVisibilityRules(reply, field); });
```
Comment (anttileppa) [inline form/index.js]: I dont agree
